[theme]
primaryColor = "#FF8C32"          # orange
backgroundColor = "#0f0f10"       # near-black
secondaryBackgroundColor = "#1c1d20" # dark grey
textColor = "#FFFFFF"             # white
font = "sans serif"
